add="bin/continuum-addProject.sh"
baseUrl="http://cvs.plexus.codehaus.org/*checkout*/plexus"

$add "$baseUrl/pom.xml"
$add "$baseUrl/plexus-containers/pom.xml"
$add "$baseUrl/plexus-containers/plexus-utils/pom.xml"
$add "$baseUrl/plexus-containers/plexus-container-api/pom.xml"
$add "$baseUrl/plexus-containers/plexus-container-default/pom.xml"
$add "$baseUrl/plexus-containers/plexus-artifact-container/pom.xml"
$add "$baseUrl/plexus-components/pom.xml"
$add "$baseUrl/plexus-components/plexus-action/pom.xml"
$add "$baseUrl/plexus-components/plexus-archiver/pom.xml"
$add "$baseUrl/plexus-components/plexus-bayesian/pom.xml"
$add "$baseUrl/plexus-components/plexus-command/pom.xml"
$add "$baseUrl/plexus-components/plexus-compiler/pom.xml"
#$add "$baseUrl/plexus-components/plexus-compiler/plexus-compiler-api/pom.xml"
#$add "$baseUrl/plexus-components/plexus-compiler/plexus-compiler-eclipse/pom.xml"
#$add "$baseUrl/plexus-components/plexus-compiler/plexus-compiler-javac/pom.xml"
#$add "$baseUrl/plexus-components/plexus-compiler/plexus-compiler-javac/pom.xml"
$add "$baseUrl/plexus-components/plexus-drools/pom.xml"
$add "$baseUrl/plexus-components/plexus-formica/pom.xml"
$add "$baseUrl/plexus-components/plexus-formica-web/pom.xml"
$add "$baseUrl/plexus-components/plexus-hibernate/pom.xml"
$add "$baseUrl/plexus-components/plexus-i18n/pom.xml"
$add "$baseUrl/plexus-components/plexus-jetty-httpd/pom.xml"
$add "$baseUrl/plexus-components/plexus-jetty/pom.xml"
$add "$baseUrl/plexus-components/plexus-mimetyper/pom.xml"
$add "$baseUrl/plexus-components/plexus-summit/pom.xml"
$add "$baseUrl/plexus-components/plexus-velocity/pom.xml"
$add "$baseUrl/plexus-components/plexus-werkflow/pom.xml"
$add "$baseUrl/plexus-components/plexus-xmlrpc/pom.xml"
$add "$baseUrl/plexus-servlet/pom.xml"
$add "$baseUrl/plexus-tools/pom.xml"
$add "$baseUrl/plexus-tools/plexus-cdc/pom.xml"
$add "$baseUrl/plexus-tools/plexus-runtime-builder/pom.xml"

