#!/bin/bash

CP=src/main/resources:apps/continuum/resources:target/classes

if [ -d apps/continuumweb/lib/ ]
then
  for jar in `find apps/continuumweb/lib/ -name '*.jar'`
  do
    CP=$CP:$jar
  done
fi

if [ -d generated-runtime/apps/continuumweb/lib ]
then
  for jar in `find generated-runtime/apps/continuumweb/lib -name '*.jar'`
  do
    CP=$CP:$jar
  done
fi

java -classpath $CP org.codehaus.continuum.standalone.CreateDdl "$@"
