#!/bin/bash

CP=
# This app requires xpp3 and plexus
CP=$CP:generated-runtime/core/xpp3-1.1.3.3.jar
CP=$CP:apps/core/xpp3-1.1.3.3.jar

CP=$CP:generated-runtime/core/plexus-0.14-SNAPSHOT.jar
CP=$CP:apps/core/plexus-0.14-SNAPSHOT.jar

CP=$CP:target/classes
CP=$CP:src/main/resources
CP=$CP:apps/continuum/resources

if [ -d apps/continuum/lib/ ]
then
  for jar in `find apps/continuum/lib/ -name '*.jar'`
  do
    CP=$CP:$jar
  done
fi

if [ -d generated-runtime/apps/continuum/lib ]
then
  for jar in `find generated-runtime/apps/continuum/lib -name '*.jar'`
  do
    CP=$CP:$jar
  done
fi

java -classpath $CP org.codehaus.continuum.utils.PomV3ToV4Converter "$@"
